name: Update app1 version on release of app1
on: [workflow_call]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get other repo
        env:
          TEMP_VERSION: "1.0.0"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
          repository: devopshelper4u/app1
          path: ./repo2
      - run: |
          cd ./repo2
          APP_VERSION=$(jq --raw-output '.version' package.json)
          echo -e "Version : $APP_VERSION"
          
      - name: Update version
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
      - run: |
          echo "1"
          jq ".myapps.internalapps.\"@devopshelper4u/app1\".version = \"$APP_VERSION\"" config/config.json > config.json
          echo "222"
          git config user.email "devops.helper.4u@gmail.com"
          git config user.name "devopshelper4u"
          echo "3333"
          git commit -m "Updated version as other repo got updated - %s"
          echo "4444"
          git push
        
